CREATE TABLE "wallet_dlcs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"eventId" VARCHAR(254) NOT NULL UNIQUE,"isInitiator" INTEGER NOT NULL, "account" VARCHAR(254) NOT NULL, "keyIndex" INTEGER NOT NULL,"initiatorWinSig" VARCHAR(254),"initiatorLoseSig" VARCHAR(254),"initiatorRefundSig" VARCHAR(254),"oracleSig" VARCHAR(254));
CREATE INDEX "wallet_dlcs_eventId_index" on "wallet_dlcs" ("eventId");

CREATE TABLE "wallet_dlc_offers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"eventId" VARCHAR(254) NOT NULL UNIQUE,"network" VARCHAR(254) NOT NULL,"oraclePubKey" VARCHAR(254) NOT NULL,"oracleRValue" VARCHAR(254) NOT NULL,"contractInfo" VARCHAR(254) NOT NULL,"penaltyTimeout" VARCHAR(254) NOT NULL,"contractMaturity" VARCHAR(254) NOT NULL,"contractTimeout" VARCHAR(254) NOT NULL,"fundingKey" VARCHAR(254) NOT NULL,"toLocalCETKey" VARCHAR(254) NOT NULL,"finalAddress" VARCHAR(254) NOT NULL,"totalCollateral" INTEGER NOT NULL,"feeRate" VARCHAR(254),"changeAddress" VARCHAR(254) NOT NULL,constraint "fk_eventId" foreign key("eventId") references "wallet_dlcs"("eventId")on update NO ACTION on delete NO ACTION);
CREATE INDEX "wallet_dlc_offers_eventId_index" on "wallet_dlc_offers" ("eventId");

CREATE TABLE "wallet_dlc_accepts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"eventId" VARCHAR(254) NOT NULL UNIQUE,"fundingKey" VARCHAR(254) NOT NULL,"toLocalCETKey" VARCHAR(254) NOT NULL,"finalAddress" VARCHAR(254) NOT NULL,"totalCollateral" INTEGER NOT NULL,"winSig" VARCHAR(254) NOT NULL,"loseSig" VARCHAR(254) NOT NULL,"refundSig" VARCHAR(254) NOT NULL,"changeAddress" VARCHAR(254) NOT NULL, constraint "fk_eventId" foreign key("eventId") references "wallet_dlcs"("eventId") on update NO ACTION on delete NO ACTION);
CREATE INDEX "wallet_dlc_accepts_eventId_index" on "wallet_dlc_accepts" ("eventId");

CREATE TABLE "wallet_dlc_funding_inputs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"eventId" VARCHAR(254) NOT NULL,"isInitiator" INTEGER NOT NULL,"outPoint" VARCHAR(254) NOT NULL UNIQUE,"output" VARCHAR(254) NOT NULL,"sigs" VARCHAR(254), constraint "fk_eventId" foreign key("eventId") references "wallet_dlcs"("eventId") on update NO ACTION on delete NO ACTION);