package org.bitcoins.core.crypto

import org.bitcoins.testkit.core.gen.{NumberGenerator, StringGenerators}
import org.bitcoins.testkit.util.BitcoinSUnitTest
import org.scalatest.Assertion
import scodec.bits.{ByteVector, HexStringSyntax}
import java.{util => ju}
import org.scalatest.compatible.Assertion
import org.bitcoins.testkit.core.gen.CryptoGenerators

class AesCryptTest extends BitcoinSUnitTest {
  behavior of "AesEncrypt"

  val password = AesPassword.fromNonEmptyString("PASSWORD")
  val badPassword = AesPassword.fromNonEmptyString("BAD_PASSWORD")

  private def getKey(bytes: ByteVector): AesKey = AesKey.fromValidBytes(bytes)
  private def getIV(bytes: ByteVector): AesIV = AesIV.fromValidBytes(bytes)

  val aesKey: AesKey =
    getKey(hex"12345678123456781234567812345678")

  val badAesKey: AesKey = getKey(aesKey.underlying.reverse)

  // TODO Update this document
  // https://gchq.github.io/CyberChef/
  /**
    * The test vectors in this test was generated by using
    * https://cryptii.com/pipes/aes-encryption
    *
    * This test only tests decryption of hard coded vectors because a random IV
    * (initialization vector) is generated each time something is encrypted.
    * Therefore encrypting something multiple times would yield a different
    * answer (and we have to store the IV with the encrypted data in the
    * AesEncryptedData case class. We also store a salt. This is not related
    * to the AES encryption itself, but the key stretching function we use to
    * transform the user provided pass phrase to a proper AES key. To go from
    * hard coded values below to something you can put into the online encryption
    * site above, you would do something like this:
    *
    * import org.bitcoins.core.crypto._
    * import scodec.bits._
    *
    * val pass = AesPassword("foobar")
    *
    * // input this into the plaintext box
    * val plainText = hex"abcdef"
    * val Right(encrypted) = AesCrypt.encrypt(plainText, pass)
    *
    * val key = AesCrypt.getSecretKey(pass, encrypted.salt)
    * val encodedKey = ByteVector(key.getEncoded).toHex // this goes in the "KEY" field
    *
    * val iv = encrypted.iv.toHex // this goes in the "IV" field
    *
    * // compare this against the encrypted text that gets outputted
    * val cipherText = encrypted.cipherText.toHex
    */
  it must "decrypt and encrypt some hard coded test vectors" in {
    case class TestVector(
        plainText: ByteVector,
        key: AesKey,
        cipherText: AesEncryptedData)

    def runTest(testVector: TestVector): Assertion = {
      val TestVector(plainText, key, cipherText) =
        testVector

      val Right(encrypted) =
        AesCrypt.encryptWithIV(plainText, cipherText.iv, key)
      assert(encrypted == cipherText)

      val Right(decrypted) = AesCrypt.decrypt(cipherText, key)
      assert(decrypted == plainText)
    }

    val first =
      TestVector(
        plainText = hex"76fe35880055e1fac950f484a815cd22",
        key = getKey(hex"2eefdf6ee2dbca83e7b7648a8f9d1897"),
        cipherText = AesEncryptedData(
          cipherText = hex"974b22d3de46a58023ddb94dac574293",
          iv = getIV(hex"889dc64377f6d993ef713c995f9c1ee5")
        )
      )

    runTest(first)

    val second = TestVector(
      plainText = hex"3a4f73044d035017d91883ebfc113da7",
      key = getKey(hex"5ce91f97ed28fd5d1172e23eb17b1baa"),
      cipherText =
        AesEncryptedData(cipherText = hex"f0ff04edc644388edb872237ac558367",
                         iv = getIV(hex"3f91d29f81d48174b25a3d0143eb833c"))
    )

    runTest(second)

    val third = TestVector(
      plainText = hex"5f6a62cb52309db4573bfed807e07bb2",
      key = getKey(hex"c62bea08786568283dafabde6d699e0f"),
      cipherText = AesEncryptedData(
        cipherText = hex"161bd64b0b4efe3561e949344e9efaaf",
        iv = getIV(hex"455014871cd34f8dcfd7c1e387987bff")
      )
    )

    runTest(third)

  }

  // to replicate:
  // echo foobar | openssl enc -aes-128-cfb -K 5ce91f97ed28fd5d1172e23eb17b1baa \
  //    -iv 455014871cd34f8dcfd7c1e387987bff -p -base64 -nosalt
  it must "pass an openssl hard coded vector" in {
    val key = getKey(hex"5CE91F97ED28FD5D1172E23EB17B1BAA")
    val plainText = "foobar"
    val Right(plainbytes) = ByteVector.encodeUtf8(plainText)
    val iv = getIV(hex"455014871CD34F8DCFD7C1E387987BFF")
    val expectedCipher = ByteVector.fromValidBase64("oE8HErg1lg==")

    val Right(encrypted) = AesCrypt.encryptWithIV(plainbytes, iv, key)

    // for some reason we end up with different cipher texts
    // decrypting works though...
    // assert(encrypted.cipherText == expectedCipher)
    assert(encrypted.iv == iv)

    val Right(decrypted) = AesCrypt.decrypt(encrypted, key)
    assert(decrypted == plainbytes)

    val Right(decryptedText) = decrypted.decodeUtf8
    assert(decryptedText == plainText)
  }

  /** REPL.it: https://repl.it/@torkelrogstad/aes-test
    * To replicate:
    * const CryptoJS = require("crypto-js")
    * const text = "The quick brown fox jumps over the lazy dog. 👻 👻";
    *
    * const key = CryptoJS.enc.Hex.parse("12345678123456781234567812345678")
    *
    * const iv = CryptoJS.enc.Hex.parse("87654321876543218765432187654321")
    *
    * const encrypted = CryptoJS.AES.encrypt(text, key, {
    *   mode: CryptoJS.mode.CFB,
    *   padding: CryptoJS.pad.NoPadding,
    *   iv: iv
    * })
    *
    * console.log(encrypted.toString())
    * // KKbLXDQUy7ajmuIJm7ZR7ugaRubqGl1JwG+x5C451JXIFofnselHVTy/u8u0Or9nV2d7Kjy0
    */
  it must "pass a hardcoded crypto-js vector where we decrypt with a key" in {
    val key = getKey(hex"12345678123456781234567812345678")
    val iv = getIV(hex"87654321876543218765432187654321")
    val expectedCipher = ByteVector.fromValidBase64(
      "KKbLXDQUy7ajmuIJm7ZR7ugaRubqGl1JwG+x5C451JXIFofnselHVTy/u8u0Or9nV2d7Kjy0")

    val plaintext = "The quick brown fox jumps over the lazy dog. 👻 👻"
    val Right(plainbytes) = ByteVector.encodeUtf8(plaintext)

    // decrypt our own encrypted data
    {
      val Right(encrypted) = AesCrypt.encryptWithIV(plainbytes, iv, key)

      assert(encrypted.iv == iv)
      assert(encrypted.cipherText == expectedCipher)

      val Right(decrypted) = AesCrypt.decrypt(encrypted, key)
      assert(decrypted == plainbytes)

      val Right(decryptedText) = decrypted.decodeUtf8
      assert(decryptedText == plaintext)
    }

    // decrypt the expected cipher text
    {
      val encrypted = AesEncryptedData(cipherText = expectedCipher, iv = iv)

      val Right(decrypted) = AesCrypt.decrypt(encrypted, key)
      assert(decrypted == plainbytes)

      val Right(decryptedText) = decrypted.decodeUtf8
      assert(decryptedText == plaintext)
    }
  }

  /** Asserts that the two bytevectors are equal expect for trailing padding */
  def assertPaddedEqual(first: ByteVector, second: ByteVector): Assertion = {
    if (first.length == second.length) {
      assert(first == second)
    } else if (first.length > second.length) {
      assert(first == second.padRight(first.length))
    } else {
      assert(first.padRight(second.length) == second)
    }
  }

  /** To replicate:
    *
    * from Crypto import Random
    * from Crypto.Cipher import AES
    * import base64
    * from binascii import unhexlify
    * import binascii
    * import math
    *
    * text = "The quick brown fox jumps over the lazy dog."
    *
    * SEGMENT_SIZE = 128
    *
    * # BLOCK_SIZE can be 16, 24 or 32
    * # key must be same number of bytes
    * BLOCK_SIZE = 16
    * key = "e67a00b510bcff7f4a0101ff5f7fb690"
    * assert len(bytes.fromhex(key)) == BLOCK_SIZE
    *
    * # IV must always be 16 bytes in CFB mode
    * IV_SIZE = 16
    * iv = "f43b7f80624e7f01123ac272beb1ff7f"
    * assert len(bytes.fromhex(iv)) == IV_SIZE
    *
    *
    * def pad(value):
    *     """Pads the given string with zero-bytes"""
    *     length = len(value)
    *
    *     pad_size = BLOCK_SIZE - (length % BLOCK_SIZE)
    *
    *     return value.ljust(length + pad_size, "\x00")
    *
    * def unpad(value):
    *     """Removes trailing zero-bytes from the given string"""
    *     while value[-1] == "\x00":
    *         value = value[:-1]
    *
    *     return value
    *
    *
    * def encrypt(in_string, key, iv):
    *     """
    *     Takes in a plain string to encrypt, as well as
    *     hex representations of the key and IV
    *     """
    *     key = unhexlify(key)
    *     iv = unhexlify(iv)
    *     aes = AES.new(key, AES.MODE_CFB, IV=iv, segment_size=SEGMENT_SIZE)
    *     padded = pad(in_string)
    *     return aes.encrypt(padded)
    *

    * def decrypt(encrypted, key, iv):
    *     """
    *     Takes in a bytes object to decrypt, as well as
    *     hex representations of the key and IV
    *     """
    *     key = unhexlify(key)
    *     iv = unhexlify(iv)
    *     aes = AES.new(key, AES.MODE_CFB, IV=iv, segment_size=SEGMENT_SIZE)
    *     decrypted = aes.decrypt(encrypted)
    *     return unpad(decrypted)
    *
    *
    * encrypted = encrypt(text, key, iv)
    * print(f"encrypted: {encrypted.hex()}")
    */
  it must "pass a hard coded test vector from pycrypto" in {
    val key = getKey(hex"e67a00b510bcff7f4a0101ff5f7fb690")
    val iv = getIV(hex"f43b7f80624e7f01123ac272beb1ff7f")
    val plainText = "The quick brown fox jumps over the lazy dog."
    val Right(plainbytes) = ByteVector.encodeUtf8(plainText)
    val expectedCipher =
      hex"09697c53d3a1e5ec5a465231e536c70428f53cb7d4030a707e42daa338ce147ec2d55c865e85dfb5072a1bf31a977cf4"

    // test encrypting and decrypting ourselves
    {
      val Right(encrypted) = AesCrypt.encryptWithIV(plainbytes, iv, key)
      // assert(encrypted.cipherText == expectedCipher)
      assert(encrypted.iv == iv)

      val Right(decrypted) = AesCrypt.decrypt(encrypted, key)
      assertPaddedEqual(decrypted, plainbytes)

      val Right(decryptedText) = decrypted.decodeUtf8
      assert(decryptedText == plainText)
    }

    // test decrypting ciphertext from pycrypto
    {
      val encrypted = AesEncryptedData(expectedCipher, iv)

      val Right(decrypted) = AesCrypt.decrypt(encrypted, key)
      assertPaddedEqual(decrypted, plainbytes)

      val Right(decryptedText) = decrypted.decodeUtf8
      assert(decryptedText.trim == plainText.trim)

    }
  }

  it must "have encryption and decryption symmetry" in {
    forAll(NumberGenerator.bytevector, CryptoGenerators.aesKey) {
      (bytes, key) =>
        val Right(encrypted) = AesCrypt.encrypt(bytes, key)
        AesCrypt.decrypt(encrypted, key) match {
          case Right(decrypted) => assert(decrypted == bytes)
          case Left(exc)        => fail(exc)
        }
    }
  }

  it must "fail to decrypt with the wrong key" in {
    forAll(NumberGenerator.bytevector.suchThat(_.nonEmpty)) { bytes =>
      val encrypted = AesCrypt.encryptExc(bytes, aesKey)
      val decryptedE = AesCrypt.decrypt(encrypted, badAesKey)
      decryptedE match {
        case Right(decrypted) =>
          assert(decrypted != bytes)
        case Left(exc) => assert(exc == AesException.BadPasswordException)
      }
    }
  }

  it must "fail to create an empty AES password" in {
    assert(AesPassword.fromString("").isEmpty)
  }
}
