name: Linux 2.13 Node & Scalajs Tests
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "! contains(github.event.pull_request.labels.*.name, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
          cache: 'sbt'
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.bitcoin-s/binaries
          key: ${{ runner.os }}-node-test-cache
      - name: run tests
        run: sbt cryptoTestJS/test coreJS/test 'set scalaJSStage in Global := FullOptStage' cryptoTestJS/test coreJS/test asyncUtilsTestJS/test coverage nodeTest/test node/coverageReport node/coverageAggregate node/coveralls dlcNodeTest/test
