name: Mac 2.13 bitcoind, eclair, and lnd rpc tests
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60
    if: "! contains(github.event.pull_request.labels.*.name, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.bitcoin-s/binaries
          key: ${{ runner.os }}-cache
      - name: run tests
        run: sbt ++2.13.8 coverage bitcoindRpcTest/test bitcoindRpc/coverageReport bitcoindRpc/coverageAggregate bitcoindRpc/coveralls eclairRpcTest/test eclairRpc/coverageReport eclairRpc/coverageAggregate eclairRpc/coveralls lndRpcTest/test esploraTest/test
